# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
exemptMilestones: true
exemptAssignees: true
exemptProjects: true
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked `stale` because it has not had
  any activity in the last 60 days. If no further activity occurs within 7
  days, it will be closed. *Closed does not mean "never"*, just that it has
  no momentum to get accomplished any time soon.

  See [CONTRIBUTING.md](CONTRIBUTING.md) for more info.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing due to staleness. *Closed does not mean "never"*, just that it has
  no momentum to get accomplished any time soon.

  See [CONTRIBUTING.md](CONTRIBUTING.md) for more info.
