version: 2
jobs:
  test-install-golang-prev:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - run:
          name: 'Test install golang (previous release)'
          command: |
            go get -v . && chamber version

  test-install-golang-current:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - run:
          name: 'Test go get install on current golang release'
          command: |
            go get -v . && chamber version

  # only need this job until 1.13 is released
  test-install-golang-1.11-GOMODULE-on:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - run:
          name: 'Test go get install on golang 1.11 GO111MODULE=on'
          command: |
            GO111MODULE=on go get -v . && chamber version

  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - run:
          name: Test
          command: |
            make test

  dist:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - run:
          name: Install nfpm, rpmbuild
          command: |
            sudo make -f Makefile.tools nfpm-debian rpmbuild-debian
      - run:
          name: Make distributables
          command: |
            make -f Makefile.release dist
      - persist_to_workspace:
          root: .
          paths: ['dist/*']

  publish:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/segmentio/chamber
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run:
          name: Install tools
          command: |
            make -f Makefile.tools github-release
            # this is all for package_cloud :/
            sudo apt update -q 
            sudo apt install -yq ruby ruby-dev build-essential
            # fixes https://askubuntu.com/questions/872399/error-failed-to-build-gem-native-extension-when-trying-to-download-rubocop
            sudo gem install rake
            sudo make -f Makefile.tools package_cloud
      - run:
          name: Release
          command: |
            make -f Makefile.release publish

workflows:
  version: 2
  test-dist-publish:
    jobs:
      - test
      - test-install-golang-prev
      - test-install-golang-current
      - test-install-golang-1.11-GOMODULE-on
      - dist:
          # needed to ensure dist happens on tag events
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - dist
          filters:
            # never publish from a branch event
            branches:
              ignore: /.*/
            # release only on tag push events like vX[.Y.Z...][-whatever]
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
