name: Build and release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04 # https://github.com/actions/virtual-environments/issues/1816

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Build
        run: make -f Makefile.release dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Updated aws-sdk-go to v1.38.22
          draft: false
          prerelease: false

      - uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist/*"]'
