name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]-[a-zA-Z0-9]+"

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Install nfpm, rpmbuild
        run: sudo make -f Makefile.tools nfpm-debian rpmbuild-debian

      - name: Make distributables
        run: make -f Makefile.release dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: "dist/*"

  publish-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: dist

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: "dist"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            dist/*

  publish-dockerhub:
    runs-on: ubuntu-latest
    needs: dist

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: "dist/*"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release
        run: make -f Makefile.release publish-dockerhub
